id: I714B3A11
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:08:39+00:00'
last_modified: '2022-06-08T08:02:14.581255+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2358
  title: གསེར་འོད་གཡང་སྐྱབས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8099':
      image_group_id: I3CN2360
      title: ''
      total_pages: 48
      order: 1
      base_file: 8099.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
