id: P008222
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:08:54.316611
source_metadata:
  id: bdr:W3CN2358
  title: གསེར་འོད་གཡང་སྐྱབས།
  author: ''
  volumes:
    65264a2292cf465ab2fde5323fab0e14:
      image_group_id: I3CN2360
      title: ''
      volume_number: 1
      total_pages: 48
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
